name: Issue Response

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check if user has write access
        id: check-contributor
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { permissions } } = await github.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });
            return permissions;
      - name: Add a comment to the new issue
        if: ${{ steps.check-contributor.outputs.result != 'write' && steps.check-contributor.outputs.result != 'admin' }}
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you @${{ github.actor }}, for bringing up this issue to help enhance our project even further! We'll review it soon. 🙌
